package de.jkamue

// Reason codes as specified in Table 2-6
open class MqttException(reasonCode: Int, message: String) : Exception(message)

class MalformedPacketMqttException(message: String) : MqttException(129, message)
class ProtocolErrorMqttException(message: String) : MqttException(130, message)
class ImplementationSpecificErrorMqttException(message: String) : MqttException(131, message)
class UnsupportedProtocolVersionMqttException(message: String) : MqttException(132, message)
class ClientIdentifierNotValidMqttException(message: String) : MqttException(133, message)
class BadUserNameOrPasswordMqttException(message: String) : MqttException(134, message)
class NotAuthorizedMqttException(message: String) : MqttException(135, message)
class ServerUnavailableMqttException(message: String) : MqttException(136, message)
class ServerBusyMqttException(message: String) : MqttException(137, message)
class BannedMqttException(message: String) : MqttException(138, message)
class ServerShuttingDownMqttException(message: String) : MqttException(139, message)
class BadAuthenticationMethodMqttException(message: String) : MqttException(140, message)
class KeepAliveTimeoutMqttException(message: String) : MqttException(141, message)
class SessionTakenOverMqttException(message: String) : MqttException(142, message)
class TopicFilterInvalidMqttException(message: String) : MqttException(143, message)
class TopicNameInvalidMqttException(message: String) : MqttException(144, message)
class PacketIdentifierInUseMqttException(message: String) : MqttException(145, message)
class PacketIdentifierNotFoundMqttException(message: String) : MqttException(146, message)
class ReceiveMaximumExceededMqttException(message: String) : MqttException(147, message)
class TopicAliasInvalidMqttException(message: String) : MqttException(148, message)
class PacketTooLargeMqttException(message: String) : MqttException(149, message)
class MessageRateTooHighMqttException(message: String) : MqttException(150, message)
class QuotaExceededMqttException(message: String) : MqttException(151, message)
class AdministrativeActionMqttException(message: String) : MqttException(152, message)
class PayloadFormatInvalidMqttException(message: String) : MqttException(153, message)
class RetainNotSupportedMqttException(message: String) : MqttException(154, message)
class QoSNotSupportedMqttException(message: String) : MqttException(155, message)
class UseAnotherServerMqttException(message: String) : MqttException(156, message)
class ServerMovedMqttException(message: String) : MqttException(157, message)
class SharedSubscriptionsNotSupportedMqttException(message: String) : MqttException(158, message)
class ConnectionRateExceededMqttException(message: String) : MqttException(159, message)
class MaximumConnectTimeMqttException(message: String) : MqttException(160, message)
class SubscriptionIdentifiersNotSupportedMqttException(message: String) : MqttException(161, message)
class WildcardSubscriptionsNotSupportedMqttException(message: String) : MqttException(162, message)